// Copies docs/results/chimera-*.json into src/physics/chimera.js (app presets).
import fs from 'node:fs';
const out = {};
for (const t of ['light', 'medium', 'strong']) {
  const f = `docs/results/chimera-${t}.json`;
  if (!fs.existsSync(f)) continue;
  const d = JSON.parse(fs.readFileSync(f)).design;
  const round = (o) => { for (const k of Object.keys(o)) { if (typeof o[k] === 'number') o[k] = +o[k].toPrecision(4); else if (o[k] && typeof o[k] === 'object') round(o[k]); } };
  round(d); d.name = `Chimera ${t}`; d.shape = 'chimera';
  out[t] = d;
}
fs.writeFileSync('src/physics/chimera.js', `// Generated by tools/export-chimera.mjs (CMA-ES with all nature-inspired features free).\nexport const CHIMERA = ${JSON.stringify(out, null, 1)};\n`);
console.log('exported chimera', Object.keys(out));
